import Dependencies
import Elementary
import Foundation
import ManualDCore
import Testing

@testable import PdfClient

struct PdfRenderingTests {
  @Test
  func roundAndFlexColumnsAndRectangularHighlighting() {
    let size = DuctSizes.SizeContainer(
      designCFM: .cooling(100), roundSize: 7.2,
      finalSize: 8, velocity: 286, flexSize: 9, height: 4, width: 13)
    let html = DuctSizeCells(size: size).render()
    #expect(html.contains("<td class=\"\">8</td><td>9</td>"))
    #expect(html.contains("<td class=\"selected\">4</td><td class=\"selected\">13</td>"))
  }

  @Test(
    .enabled(
      if: FileManager.default.isExecutableFile(atPath: "/usr/bin/weasyprint")
        && FileManager.default.isExecutableFile(atPath: "/usr/bin/pdftotext")),
    arguments: [false, true])
  func rendersCompleteReport(large: Bool) async throws {
    try await withDependencies {
      $0.uuid = .incrementing
      $0.date.now = reportDate
      $0.fileClient.writeFile = { contents, path in
        try contents.write(toFile: path, atomically: true, encoding: .utf8)
      }
      $0.fileClient.removeFile = { try FileManager.default.removeItem(atPath: $0) }
      $0.environment = .init()
    } operation: {
      let result = try await PdfClient.liveValue.generatePdf(request: reportFixture(large: large))
      defer {
        try? FileManager.default.removeItem(atPath: result.htmlPath)
        try? FileManager.default.removeItem(atPath: result.pdfPath)
      }
      let process = Process()
      process.executableURL = URL(fileURLWithPath: "/usr/bin/pdftotext")
      process.arguments = ["-layout", result.pdfPath, "-"]
      let pipe = Pipe()
      process.standardOutput = pipe
      try process.run()
      let data = pipe.fileHandleForReading.readDataToEndOfFile()
      process.waitUntilExit()
      #expect(process.terminationStatus == 0)
      let text = String(decoding: data, as: UTF8.self)
      let pages = text.components(separatedBy: "\u{c}").filter {
        !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
      }
      #expect(large ? pages.count > 3 : pages.count == 3)
      for (index, page) in pages.enumerated() {
        #expect(page.contains("RESIDENTIAL DUCT DESIGN"))
        #expect(page.contains("Maple House"))
        #expect(page.contains("\(index + 1) / \(pages.count)"))
      }
      for heading in ["Duct schedule", "Design calculations", "Loads & airflow"] {
        #expect(text.contains(heading))
      }
      if large {
        for index in 1...75 { #expect(text.contains("Room \(index)")) }
        for index in 1...55 { #expect(text.contains("Branch \(index)")) }
        for index in 1...100 { #expect(text.contains("\(index)-a")) }
        #expect(text.contains("Component 30"))
        #expect(text.components(separatedBy: "Room / register").count > 3)
        #expect(text.components(separatedBy: "Fitting").count > 2)
      }
      // Optional review artifacts are generated by the same converter used by live exports.
      if let output = ProcessInfo.processInfo.environment["PDF_REVIEW_OUTPUT"] {
        let directory = URL(fileURLWithPath: output, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let name = large ? "large" : "mixed"
        try Data(contentsOf: URL(fileURLWithPath: result.pdfPath)).write(
          to: directory.appendingPathComponent("\(name).pdf"))
        try Data(contentsOf: URL(fileURLWithPath: result.htmlPath)).write(
          to: directory.appendingPathComponent("\(name).html"))
      }
    }
  }
}
