name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Linux Tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup just
      uses: https://git.housh.dev/actions/setup-just.git@v1
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3 
    - name: Run tests
      run: just docker_tag=test test-docker
