#!/usr/bin/env python3
"""Build a reference catalog from approved artwork metadata; no production rules."""
import argparse
import json
import xml.etree.ElementTree as ET
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'Public/images/fittings'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output', type=Path, default=ROOT / 'Public/fittings',
                    help='Destination directory (defaults to the served fitting reference).')
OUT = parser.parse_args().output
OUT.mkdir(parents=True, exist_ok=True)
SOURCES = {1:'catalog.json',2:'group-2-restored/manifest.json',3:'group-3-individual/manifest.json',4:'group-4-enhanced/manifest.json',5:'group-5-shapes/manifest.json',6:'group-6-enhanced/manifest.json',7:'group-7-options/manifest.json',8:'group-8/manifest.json',9:'group-9/manifest.json',10:'group-10/manifest.json',12:'group-12/manifest.json'}
items=[]
for group, path in SOURCES.items():
    doc=json.loads((ART/path).read_text())
    for item in doc.get('items',doc.get('fittings',[])):
        if group==1 and item['group']!=1: continue
        assert item['status']=='visually-approved', item['id']
        image=item.get('svg',item.get('image'))
        assert (ROOT/'Public'/image.lstrip('/')).is_file(), image
        source=item.get('source',doc.get('source',{}))
        entry={'id':item['id'],'group':group,'code':item.get('sourceFittingId',item.get('fittingId',item.get('fittingNumber',item['id']))),'name':item['name'],'image':image,'source':source,'page':str(source.get('printedPage') or '–'.join(map(str,source.get('printedPages',[]))) or 'See PDF'),'notes':item.get('notes',[]),'conditions':item.get('referenceConditions',doc.get('referenceConditions',{})),'values':item.get('referenceValues',{}),'manifest':path}
        for src,dest in [('referenceEquivalentLengthTable','ratioTable'),('referenceEquivalentLengthByDownstreamBranches','branches'),('ductShape','shape'),('connectionShapes','connectionShapes'),('artworkView','view'),('variant','variant'),('countingRule','countingRule'),('equivalentLengthAdjustment','adjustment')]:
            if item.get(src) is not None: entry[dest]=item[src]
        fixed=item.get('referenceEquivalentLengthFeet')
        if fixed is None: fixed=entry['values'].get('equivalentLengthFeet')
        if isinstance(fixed,(float,int)):entry['fixed']=fixed
        if group == 1:
            entry['viewport'] = [0, 95, 640, 350]
        if group == 4:
            svg_root = ET.parse(ROOT/'Public'/image.lstrip('/')).getroot()
            image_node = svg_root.find('{http://www.w3.org/2000/svg}image')
            if image_node is None:
                image_node = svg_root.find('{http://www.w3.org/2000/svg}svg')
            x, y, width, height = [float(image_node.get(k)) for k in ['x','y','width','height']]
            pixel_width, pixel_height = item['embeddedRasterSize']
            scale = min(width/pixel_width, height/pixel_height)
            art_width, art_height = pixel_width*scale, pixel_height*scale
            entry['viewport'] = [round(x+(width-art_width)/2-5,3),round(y+(height-art_height)/2-5,3),round(art_width+10,3),round(art_height+10,3)]
        items.append(entry)
for kind,name in [('junction-box','Flex junction box')]:
    items.append({'id':'11-'+kind,'code':'Group 11','group':11,'name':name,'image':'concepts/11-'+kind+'.svg','page':'181','source':{'pdfPage':42},'notes':[],'conditions':{'frictionRateIwcPer100Feet':.08,'velocityFpm':'Selected table row'},'values':{},'concept':kind})
items.sort(key=lambda x:x['group'])
assert len({x['id'] for x in items})==len(items)
(OUT/'catalog-data.js').write_text('// Generated by scripts/build_fitting_reference_catalog.py.\nwindow.FITTINGS = '+json.dumps(items,separators=(',',':'))+';\n')
print(f'{len(items)} drawing choices; groups '+', '.join(str(g) for g in sorted({x['group'] for x in items})))
