// Run against a disposable application. Creates a user, template, and project.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const base = process.env.FITTING_APP_URL || 'http://localhost:8081';
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
    const password = require('node:crypto').randomUUID();
    const signup = await context.request.post(base + '/signup', { form: { email: `template-browser-${Date.now()}@example.test`, password, confirmPassword: password } });
    const userID = (await signup.text()).match(/name="userID" value="([^"]+)"/)[1];
    await context.request.post(base + '/signup/profile', { form: { userID, firstName: 'Template', lastName: 'Review', companyName: 'QA', streetAddress: '1 Test Street', city: 'Cincinnati', state: 'OH', zipCode: '45202', theme: 'dark' } });
    const project = await context.request.post(base + '/projects', { form: { name: 'Template browser review', streetAddress: '1 Test Street', city: 'Cincinnati', state: 'OH', zipCode: '45202' } });
    const projectID = (await project.text()).match(/projects\/([0-9A-Fa-f-]{36})/)[1];
    const page = await context.newPage(), errors = [], prompts = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => { prompts.push(dialog.type()); dialog.accept(); });
    await page.goto(base + '/path-templates/new/supply');
    await page.locator('[data-config=name]').fill('Browser reviewed supply');
    await page.locator('[data-config=name]').press('Tab');
    const downloaded = page.waitForEvent('download');
    await page.locator('[data-action=export-template]').click();
    const file = await downloaded, exportPath = await file.path();
    const exported = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
    assert.equal(exported.name, 'Browser reviewed supply');
    assert.equal(exported.steps.length, 5);
    assert.equal(await page.locator('[data-theme=dark]').count(), 1);
    await page.screenshot({ path: '/tmp/templates-editor-desktop.png', animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: '/tmp/templates-editor-mobile.png', animations: 'disabled' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('[data-action=try]').click();
    await page.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Supply trunk branch takeoff');
    await page.locator('[data-action=exit-trial]').first().click();
    assert.equal(await page.locator('[data-config=name]').inputValue(), 'Browser reviewed supply');
    await page.locator('[data-action=save-template]').click();
    await page.waitForURL(/\/path-templates\/[0-9A-Fa-f-]{36}$/);
    const templateID = page.url().split('/').pop();
    await page.goto(`${base}/projects/${projectID}/effective-lengths`);
    assert.equal(await page.getByRole('link', { name: 'Add equivalent length', exact: true }).count(), 1);
    assert.equal(await page.getByRole('link', { name: 'From template', exact: true }).count(), 0);
    const add = page.getByRole('link', { name: 'Add equivalent length', exact: true });
    assert.equal((await add.innerText()).trim(), '', 'The add control should display only its plus icon');
    assert.equal(await add.locator('svg').count(), 1);
    await add.click();
    const modal = page.locator('#fitting-path');
    await modal.waitFor({ state: 'visible' });
    assert(await modal.evaluate(dialog => dialog.matches(':modal')));
    const carriedName = 'Supply + "East" & <West>';
    await page.locator('#path-name').fill(carriedName);
    await page.locator('#path-straight').fill('10, invalid');
    await modal.getByRole('link', { name: 'From template', exact: true }).click();
    await page.locator('#path-status').filter({ hasText: 'positive whole feet' }).waitFor();
    assert(await modal.evaluate(dialog => dialog.matches(':modal')));
    await page.locator('#path-straight').fill('10, 25, 15');
    assert.equal(await page.locator('.coverage #path-from-template').count(), 1);
    await page.screenshot({ path: '/tmp/template-handoff-desktop.png', animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await modal.evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth));
    await page.locator('#path-from-template').scrollIntoViewIfNeeded();
    await page.screenshot({ path: '/tmp/template-handoff-mobile.png', animations: 'disabled' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    const editorURL = page.url(), promptCount = prompts.length;
    await page.route('**/guided?draft=*', route => route.fulfill({ status: 500, body: 'Test failure' }));
    await modal.getByRole('link', { name: 'From template', exact: true }).click();
    await page.locator('#path-status').filter({ hasText: 'Unable to load templates' }).waitFor();
    assert.equal(await page.locator('#path-name').inputValue(), carriedName);
    await page.unroute('**/guided?draft=*');
    await modal.getByRole('link', { name: 'From template', exact: true }).click();
    await modal.getByRole('heading', { name: 'Choose a path template', exact: true }).waitFor();
    assert.equal(page.url(), editorURL);
    assert(await modal.evaluate(dialog => dialog.matches(':modal')));
    await page.screenshot({ path: '/tmp/template-modal-chooser.png', animations: 'disabled' });
    // Starter POSTs use this same dialog and preserve the original form for Back.
    await modal.getByRole('button', { name: 'Use starter return', exact: true }).click();
    await modal.locator('#path-template-data').waitFor({ state: 'attached' });
    const starterData = JSON.parse(await modal.locator('#path-template-data').textContent());
    assert.deepEqual(starterData.initialValues, { name: carriedName, straightLengths: [10, 25, 15] });
    await modal.getByRole('button', { name: 'Back to path', exact: true }).click();
    assert.equal(await page.locator('#path-name').inputValue(), carriedName);
    assert.equal(await page.locator('#path-straight').inputValue(), '10, 25, 15');
    await modal.getByRole('link', { name: 'From template', exact: true }).click();
    await modal.locator('.card').filter({ hasText: 'Browser reviewed supply' }).getByRole('link', { name: 'Use template', exact: true }).click();
    await modal.locator('#path-template-data').waitFor({ state: 'attached' });
    assert.equal(page.url(), editorURL);
    assert.equal(prompts.length, promptCount, 'Template transitions must not show leave-site or discard prompts');
    await page.screenshot({ path: '/tmp/template-modal-guided.png', animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await modal.evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth));
    await page.screenshot({ path: '/tmp/template-modal-guided-mobile.png', animations: 'disabled' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    const initialData = JSON.parse(await page.locator('#path-template-data').textContent());
    assert.deepEqual(initialData.initialValues, { name: carriedName, straightLengths: [10, 25, 15] });
    await page.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Supply trunk branch takeoff');
    await page.locator('[data-action=skip]').click();
    await page.locator('[data-action=choose][data-id="4G"]').click();
    await page.locator('[data-quantity="8A-4-or-5-piece"]').fill('2');
    await page.locator('[data-action=done]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Transitions');
    await page.locator('[data-action=skip]').click();
    assert.equal(await page.locator('[data-path=name]').inputValue(), carriedName);
    assert.equal(await page.locator('[data-path=straight]').inputValue(), '10, 25, 15');
    await page.locator('[data-action=save-path]').click();
    await page.waitForURL(`**/projects/${projectID}/effective-lengths`);
    assert.equal(prompts.length, promptCount, 'Saving the template path must not show a leave-site warning');
    await page.getByRole('link', { name: 'Edit', exact: true }).click();
    await page.waitForURL(/\/guided\/edit\//);
    const saved = JSON.parse(await page.locator('#path-template-data').textContent()).path;
    assert.equal(saved.templateSnapshot.templateID, templateID);
    assert.equal(saved.name, carriedName);
    assert.deepEqual(saved.straightLengths, [10, 25, 15]);
    assert.equal(saved.groups.length, 3);
    assert.equal(saved.groups[2].quantity, 2);
    assert.equal(saved.groups[2].fitting.calculation.catalogRevision, 'fitting-catalog-v14');
    await page.screenshot({ path: '/tmp/templates-guided-desktop.png', animations: 'disabled' });
    await page.goto(base + '/path-templates/import');
    await page.locator('#import-template-file').setInputFiles(exportPath);
    await page.locator('[data-action=import-template]').waitFor();
    await page.locator('[data-action=import-template]').click();
    await page.waitForURL(/\/path-templates\/[0-9A-Fa-f-]{36}$/);
    assert.notEqual(page.url().split('/').pop(), templateID);
    assert.deepEqual(errors, []);
    console.log('PASS: template editor, actual JSON download/import, independent Try, desktop/mobile theme, existing picker entry, guided save/reopen, and current catalog snapshots.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
