const assert = require('node:assert/strict');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
const { chromium } = require('playwright');
const origin = process.env.DUCTCALC_FILTER_ORIGIN || `http://127.0.0.1:${fs.readFileSync('.dev-port', 'utf8').trim()}`;
assert(['localhost', '127.0.0.1'].includes(new URL(origin).hostname), 'Use an isolated local app');
(async () => {
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({ baseURL: origin, viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const page = await context.newPage(); const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const email = `filters-${randomUUID()}@example.test`;
    const signup = await context.request.post('/signup', { form: { email, password: 'TestPassword123!', confirmPassword: 'TestPassword123!' } });
    assert.equal(signup.status(), 200);
    const created = await context.request.post('/projects', { form: { name: 'Filter library browser test', streetAddress: '1 Test St', city: 'Test', state: 'OH', zipCode: '45050' } });
    assert.equal(created.status(), 200);
    const projectID = (await created.text()).match(/data-project-id="([^"]+)"/)[1];
    const project = `/projects/${projectID}`;
    await context.request.post(`${project}/equipment`, { form: { projectID, heatingCFM: '1000', coolingCFM: '1200', staticPressure: '0.5' } });
    await page.goto('/filters');
    await page.evaluate(() => window.dispatchEvent(new Event('focus')));
    async function saved(operation) {
      const revision = await page.locator('#filter-account').getAttribute('data-filter-revision');
      await operation();
      await page.waitForFunction(revision => document.querySelector('#filter-account')?.dataset.filterRevision !== revision, revision);
    }
    await page.getByRole('button', { name: 'Add filter', exact: true }).click();
    const editor = page.locator('#filter-editor[open]'); await editor.waitFor();
    await editor.locator('[name=manufacturer]').fill('Example brand');
    await editor.locator('[name=model]').fill('Custom media');
    await editor.locator('[name=description]').fill('MERV 13 · 20 x 25 x 4');
    await editor.locator('[name=favorite]').check();
    await editor.locator('[name=pointAirflow]').nth(0).fill('400');
    await editor.locator('[name=pointDrop]').nth(0).fill('0.015');
    await editor.locator('[name=pointAirflow]').nth(1).fill('1600');
    await editor.locator('[name=pointDrop]').nth(1).fill('0.12');
    await editor.getByRole('button', { name: 'Check chart' }).click();
    await editor.locator('#filter-chart-preview').getByText('0.09 in. w.c.', { exact: true }).waitFor();
    await saved(() => editor.getByRole('button', { name: 'Save filter' }).click());
    const search = page.getByRole('searchbox', { name: 'Search filters' });
    await search.fill('Example brand');
    await search.press('Enter');
    await page.waitForURL(/q=Example\+brand/);
    assert.equal(await page.getByRole('button', { name: 'Edit Example brand Custom media', exact: true }).count(), 1);
    assert.equal(await search.inputValue(), 'Example brand');
    await search.fill('Example+brand');
    await search.press('Enter');
    await page.waitForURL(/q=Example%2Bbrand/);
    assert.equal(await page.getByRole('button', { name: 'Edit Example brand Custom media', exact: true }).count(), 0);
    await page.goto('/filters');
    await page.reload();
    await page.getByRole('button', { name: 'Edit Example brand Custom media', exact: true }).click();
    assert.equal(await editor.locator('[name=pointDrop]').nth(0).inputValue(), '0.015');
    await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.locator('.filter-tabs').getByRole('link', { name: 'Design preferences' }).click();
    await page.locator('[name=maximumPressureDrop]').fill('0.08');
    await saved(() => page.locator('[data-filter-maximum] button').click());
    assert.match(await page.locator('#filter-account').innerText(), /No favorite meets/);
    await page.locator('[name=maximumPressureDrop]').fill('0.15');
    await saved(() => page.locator('[data-filter-maximum] button').click());
    assert.match(await page.locator('#filter-account').innerText(), /Suggests Example brand Custom media/);
    await page.goto(`${project}/friction-rate`);
    await page.getByRole('button', { name: 'From template', exact: true }).click();
    await page.getByRole('button', { name: 'Use Furnace + evaporator coil template', exact: true }).click();
    const lookup = page.locator('#filterLookup[open]'); await lookup.waitFor();
    await lookup.locator('[name=allowance]').fill('0.03');
    await lookup.getByRole('button', { name: 'Use Example brand Custom media, 0.06 inches of water column', exact: true }).first().waitFor();
    await lookup.getByRole('button', { name: 'Use Example brand Custom media, 0.06 inches of water column', exact: true }).first().click();
    await page.locator('#filterLookup[open]').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('.loss-table tbody tr').count(), 5);
    assert.match(await page.locator('.loss-table').innerText(), /Custom media filter/);
    const loss = page.locator('.loss-table tr').filter({ hasText: 'Custom media filter' });
    assert.equal(await loss.locator('input[type=number]').inputValue(), '0.06');
    await page.getByRole('button', { name: 'Look up filter', exact: true }).click();
    await lookup.waitFor();
    assert.equal(await lookup.locator('[name=allowance]').inputValue(), '0.03');
    await lookup.locator('[name=allowance]').fill('0.10');
    await lookup.getByRole('button', { name: 'Use Example brand Custom media, 0.00 inches of water column', exact: true }).first().click();
    await page.locator('#filterLookup[open]').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('.loss-table tbody tr').count(), 4);
    await page.getByRole('button', { name: 'Use template', exact: true }).click();
    await page.getByRole('button', { name: 'Use Air handler template', exact: true }).click();
    await lookup.waitFor(); await lookup.getByRole('button', { name: 'Skip filter', exact: true }).click();
    assert.equal(await page.locator('.loss-table tbody tr').count(), 3);
    await page.goto('/filters');
    await page.getByRole('button', { name: 'Delete Example brand Custom media', exact: true }).click();
    await page.locator('#filter-delete-dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByRole('button', { name: 'Delete Example brand Custom media', exact: true }).click();
    await saved(() => page.locator('#filter-delete-dialog').getByRole('button', { name: 'Delete filter', exact: true }).click());
    assert.equal(await page.getByRole('button', { name: 'Edit Example brand Custom media', exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Delete Aprilaire 213', exact: true }).click();
    await saved(() => page.locator('#filter-delete-dialog').getByRole('button', { name: 'Delete filter', exact: true }).click());
    await page.getByRole('button', { name: 'Restore Aprilaire filters', exact: true }).click();
    await saved(() => page.locator('#restore-filters').getByRole('button', { name: 'Restore selected' }).click());
    assert.equal(await page.getByRole('button', { name: 'Edit Aprilaire 213', exact: true }).count(), 1);
    const stale = await context.newPage(); await stale.goto('/filters');
    await stale.getByRole('button', { name: 'Edit Aprilaire 213', exact: true }).click();
    await saved(() => page.getByRole('button', { name: 'Add Aprilaire 213 to favorites', exact: true }).click());
    await stale.locator('#filter-editor').getByRole('button', { name: 'Save filter' }).click();
    await stale.locator('[data-filter-editor-error]').getByText(/changed in another tab/).waitFor();
    await stale.close();
    await page.goto('/filters?tab=preferences');
    await page.locator('[data-filter-add-favorite] select').selectOption('513');
    await saved(() => page.getByRole('button', { name: 'Add favorite', exact: true }).click());
    const cutoff = page.getByRole('form', { name: 'Airflow preference for Aprilaire 213', exact: true });
    await cutoff.getByLabel('Suggest below').fill('1200');
    await saved(() => cutoff.getByRole('button', { name: 'Save', exact: true }).click());
    await page.reload();
    assert.equal(await cutoff.getByLabel('Suggest below').inputValue(), '1200');
    assert.match(await page.locator('#filter-account').innerText(), /Suggests Aprilaire 513/);
    assert.match(await page.locator('#filter-account').innerText(), /Skipped: At or above your 1200 CFM cutoff/);
    await page.getByLabel('Example airflow').fill('1199');
    await page.getByRole('button', { name: 'Check', exact: true }).click();
    await page.waitForURL(/airflow=1199/);
    assert.match(await page.locator('#filter-account').innerText(), /Suggests Aprilaire 213/);
    await page.goto('/filters?tab=preferences');
    await cutoff.getByLabel('Suggest below').fill('');
    await saved(() => cutoff.getByRole('button', { name: 'Save', exact: true }).click());
    assert.match(await page.locator('#filter-account').innerText(), /Suggests Aprilaire 213/);
    await cutoff.getByLabel('Suggest below').fill('1200');
    await saved(() => cutoff.getByRole('button', { name: 'Save', exact: true }).click());
    await page.goto(`${project}/friction-rate`);
    await page.getByRole('button', { name: 'Look up filter', exact: true }).click();
    await lookup.waitFor();
    await lookup.getByRole('button', { name: 'Use Aprilaire 513, 0.00 inches of water column', exact: true }).first().waitFor();
    assert.equal(await lookup.locator('button[name=model]').filter({ hasText: 'Use Aprilaire 513' }).count(), 1);
    await lookup.locator('[data-filter-hide-over]').check();
    const manualChoice = lookup.getByRole('button', { name: 'Use Aprilaire 213, 0.05 inches of water column', exact: true });
    assert(await manualChoice.isVisible(), 'Cutoff must not hide manual selection');
    assert(await manualChoice.isEnabled(), 'Cutoff must not disable manual selection');
    await manualChoice.click();
    await page.locator('#filterLookup[open]').waitFor({ state: 'hidden' });
    const manualLoss = page.locator('.loss-table tr').filter({ hasText: 'Aprilaire 213 filter' });
    assert.equal(await manualLoss.locator('input[type=number]').inputValue(), '0.05');
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 1000 });
      for (const path of ['/filters', '/filters?tab=preferences']) {
        await page.goto(path);
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${path} overflows at ${width}`);
        await page.screenshot({ path: `/tmp/ductcalc-filters-${width}-${path.includes('?') ? 'preferences' : 'library'}.png`, fullPage: true });
      }
    }
    for (const path of ['/filters?airflow=2500', '/filters?tab=preferences']) {
      await page.goto(path); await page.addScriptTag({ content: require('axe-core').source });
      for (const theme of ['light', 'dark']) {
        await page.evaluate(theme => {
          document.documentElement.dataset.theme = theme;
          document.querySelector('main').closest('[data-theme]').dataset.theme = theme;
        }, theme);
        await page.waitForTimeout(250);
        const scan = await page.evaluate(() => axe.run('#filter-account'));
        assert.deepEqual(scan.violations.map(v => v.id), [], `${path} accessibility in ${theme}`);
      }
    }
    await page.goto('/filters'); await page.getByRole('button', { name: 'Edit Aprilaire 213', exact: true }).click();
    await editor.waitFor();
    assert(await editor.locator('.filter-chart').evaluate(el => el.scrollWidth <= el.clientWidth));
    await editor.evaluate(el => Promise.all(el.getAnimations({ subtree: true }).map(animation => animation.finished)));
    await page.screenshot({ path: '/tmp/ductcalc-filter-editor-320.png' });
    await page.addScriptTag({ content: require('axe-core').source });
    const accessibility = await page.evaluate(() => axe.run('#filter-editor'));
    assert.deepEqual(accessibility.violations.map(v => v.id), []);
    assert.deepEqual(errors, []);
    console.log('PASS: account CRUD, chart preview/precision, preferences, cutoff boundaries/persistence/clearing, manual filter selection beyond cutoff, template filter step, allowance subtraction/coverage, skipping, deletion/restore, stale edits, mobile layout, and accessibility.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
