const { saveAndReopen } = require('./fitting_browser_helpers.cjs');
// Run after check_fitting_path.cjs; uses that isolated test account and project.
const{chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});try{
const context=await b.newContext({storageState:'/tmp/fitting-review-auth.json',viewport:{width:1440,height:1000}}),p=await context.newPage();p.on('dialog',d=>d.accept());
const url=fs.readFileSync('/tmp/fitting-review-path.txt','utf8').trim(),endpoint=url.split('/editor')[0];await p.goto(url);
// Save must use Swift inputs rather than a browser-supplied result or provenance.
const original=JSON.parse(await p.locator('#fitting-path').getAttribute('data-baseline'));
const rows=JSON.parse(await p.locator('#fitting-path').getAttribute('data-rows'));
const catalog=rows.find(entry=>entry.row.fittingID==='8O');catalog.savedIndex=null;catalog.row.feet=999999;catalog.row.calculation.equivalentLengthFeet=999999;
let response=await p.request.post(endpoint+'/save-path',{form:{payload:JSON.stringify({baseline:null,name:'Server-authority check '+Date.now(),pathType:'supply',straightLengths:[],entries:[catalog]})}});let text=await response.text();assert(text.includes('data-saved-path'),text);const id=text.match(/data-saved-path="([^"]+)"/)[1];
await p.goto(endpoint+'/editor?id='+id);let saved=JSON.parse(await p.locator('#fitting-path').getAttribute('data-baseline'));assert.equal(saved.groups[0].value,235);assert.equal(saved.groups[0].fitting.calculation.equivalentLengthFeet,235);
// Editing retains durable row identity and updates the authoritative calculation.
const rowID=saved.groups[0].fitting.id;await p.locator('[data-edit-row]').click();await p.locator('#edit-fitting [data-row]').waitFor();await p.locator('#edit-fitting [name=insideCornerRadius]').selectOption('oneQuarter');await p.waitForFunction(()=>document.querySelector('#edit-fitting .fp-result').textContent.includes('90 ft'));await p.locator('#edit-fitting [data-row]').click();await saveAndReopen(p);await p.waitForFunction(()=>JSON.parse(document.querySelector('#fitting-path').dataset.baseline).groups[0].value===90);saved=JSON.parse(await p.locator('#fitting-path').getAttribute('data-baseline'));assert.equal(saved.groups[0].fitting.id,rowID);
// A stale baseline cannot overwrite the edited path.
response=await p.request.post(endpoint+'/save-path',{form:{payload:JSON.stringify({baseline:{...saved,name:'Old name'},name:'Overwrite',pathType:'supply',straightLengths:[],entries:[{...catalog,savedIndex:0}]})}});assert.match(await response.text(),/changed since you opened/);
// Group 6 exposes two alternatives, and saves the selected path contribution.
await p.goto(endpoint+'/editor');await p.locator('#path-name').fill('Return contribution '+Date.now());await p.locator('#path-type').selectOption('return');await p.locator('[data-open-picker]').click();const carousel=p.locator('[data-path-carousel="return"]');await carousel.getByRole('button',{name:/^Show Group 6:/}).click();await carousel.locator('.is-current [data-choose-group]').click();const card=p.locator('[data-catalog-id="6A"]');await card.locator('[name=branchCFM]').fill('200');await card.locator('[name=totalCFM]').fill('1000');await card.locator('[data-row]').first().waitFor();assert.equal(await card.locator('[data-row]').count(),2);const branch=JSON.parse(await card.locator('[data-row]').first().getAttribute('data-row')).feet;await card.locator('[data-row]').first().click();await saveAndReopen(p);await p.waitForURL(/editor\?id=/);saved=JSON.parse(await p.locator('#fitting-path').getAttribute('data-baseline'));assert.equal(saved.groups[0].value,branch);assert.equal(saved.groups[0].fitting.column,'branch');
// Carousel wraps in both directions, including keyboard navigation.
await p.locator('[data-open-picker]').click();const returnCarousel=p.locator('[data-path-carousel="return"]');const first=await returnCarousel.locator('.is-current').getAttribute('data-carousel-index');await returnCarousel.locator('[data-carousel-step="-1"]').click();assert.equal(await returnCarousel.locator('.is-current').getAttribute('data-carousel-index'),'6');await returnCarousel.locator('[data-carousel-step="1"]').click();assert.equal(await returnCarousel.locator('.is-current').getAttribute('data-carousel-index'),first);
console.log('PASS: server-authoritative calculations, durable edited row IDs, stale-save rejection, Group 6 saved column, looping carousel.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
