// Requires Playwright with Chromium and a running live app. See docs/fitting-picker-preview.md.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const result=()=>page.locator('#fp-result');
 async function open(id,group){await page.locator(`[data-group="${group}"]`).click();await page.locator(`[data-fitting-id="${id}"]`).click();}
 async function ready(){await page.locator('#fp-result [data-row]').first().waitFor();}
 await page.goto(`${process.env.FITTING_PICKER_URL || 'http://localhost:8081'}/fittings`);
 await open('11-junction-box',11); await ready();
 assert.match(await result().innerText(),/60 ft/);
 assert.equal(await page.locator('[name=bendVelocity]').isVisible(),false);
 await page.locator('[name=suppliedBend]').check();
 await page.locator('[name=bendVelocity]').selectOption('900');
 await ready(); await page.waitForFunction(()=>document.querySelector('#fp-result').textContent.includes('80 ft'));
 await page.locator('[name=suppliedBend]').uncheck();await ready();
 await page.waitForFunction(()=>document.querySelector('#fp-result').textContent.includes('60 ft'));
 await page.locator('[name=suppliedBend]').check();await ready();
 assert.equal(await page.locator('[name=bendVelocity]').inputValue(),'900');
 await page.waitForFunction(()=>document.querySelector('#fp-result').textContent.includes('80 ft'));
 await page.locator('[data-row]').click();
 assert.equal(await page.locator('#fp-total').innerText(),'80 ft');
 await page.locator('#fp-straight').fill('12.375');await page.locator('#fp-straight').press('Tab');
 await page.locator('#fp-rows input').fill('2');await page.locator('#fp-rows input').press('Tab');
 assert.equal(await page.locator('#fp-total').innerText(),'172.375 ft');
 await page.getByRole('button',{name:'Edit',exact:true}).click();await ready();
 assert.equal(await page.locator('[name=bendVelocity]').inputValue(),'900');
 await page.locator('[name=flexVelocity]').selectOption('800');await ready();
 await page.waitForFunction(()=>document.querySelector('#fp-result').textContent.includes('95 ft'));
 await page.locator('[data-row]').click();assert.equal(await page.locator('#fp-total').innerText(),'202.375 ft');
 await open('8O',8);await ready();assert.equal(await page.locator('[name=insideCornerRadius]').inputValue(),'mitered');
 await page.locator('[name=insideCornerRadius]').selectOption('');
 assert.equal(await page.locator('[data-row]').count(),0);
 await page.waitForTimeout(300);assert.equal(await page.locator('[data-row]').count(),0);
 await page.locator('[data-close-picker]').click();
 await page.locator('#fp-reference-open').click();
 await page.locator('[name=code]').fill('4AG');await page.locator('[name=length]').fill('61.375');await page.getByRole('button',{name:'Check entry',exact:true}).click();
 await page.locator('#fp-reference-result [data-row]').click();
 assert.equal(await page.locator('#fp-total').innerText(),'263.75 ft');
 await page.reload();assert.equal(await page.locator('#fp-total').innerText(),'263.75 ft');
 await page.locator('a[href="/fittings?type=return"]').click();assert.equal(await page.locator('#fp-total').innerText(),'0 ft');
 await page.locator('[data-group="6"]').click();await page.locator('[data-panel="6"] [data-fitting-id]').first().click();
 await page.locator('[name=branchCFM]').fill('200');await page.locator('[name=totalCFM]').fill('1000');await ready();
 assert.equal(await page.locator('#fp-result [data-row]').count(),2);
 await page.locator('#fp-result [data-row]').first().click();
 await page.locator('a[href="/fittings?type=supply"]').click();assert.equal(await page.locator('#fp-total').innerText(),'263.75 ft');
 await page.locator('[data-group="11"]').click();await page.screenshot({path:'/tmp/picker-path.png'});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
 await page.screenshot({path:'/tmp/picker-mobile.png'});
 await open('11-junction-box',11);await ready();
 assert.equal(await page.evaluate(()=>document.querySelector('#fp-dialog').scrollWidth <= document.querySelector('#fp-dialog').clientWidth),true);
 await page.screenshot({path:'/tmp/picker-mobile-flex.png'});
 assert.deepEqual(errors,[]);console.log('PASS: flex controls, edit, quantities, fractional totals, missing inputs, quick entry, reload, separate paths, Group 6, mobile overflow, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
