// Run after check_fitting_path.cjs against the same disposable application.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ storageState: '/tmp/fitting-review-auth.json', viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage(), errors = [], prompts = [];
    page.on('pageerror', error => errors.push(error.message));
    let accept = false;
    page.on('dialog', async dialog => { prompts.push(dialog.type()); await (accept ? dialog.accept() : dialog.dismiss()); });
    const savedURL = fs.readFileSync('/tmp/fitting-review-path.txt', 'utf8').trim();
    const url = new URL(savedURL); url.search = '';
    const listURL = url.href.replace(/\/editor$/, '');
    await page.goto(url.href);
    const modal = page.locator('#fitting-path');
    await modal.waitFor();
    await page.locator('#path-name').fill('Retain this original draft');
    await page.locator('#path-straight').fill('10, 15');
    await page.locator('#quick-entry-open').click();
    await page.locator('#reference-form [name=code]').fill('8A');
    await page.locator('#reference-form [name=length]').fill('12.5');
    await page.locator('#reference-form').evaluate(form => form.requestSubmit());
    await page.locator('#reference-result [data-row]').click();
    await page.locator('#path-rows [data-row-id]').waitFor();
    const draftRows = await page.locator('#path-rows').innerText();
    await page.locator('#path-from-template').click();
    await modal.getByRole('heading', { name: 'Choose a path template', exact: true }).waitFor();
    const starter = modal.getByRole('button', { name: 'Use starter supply', exact: true });
    if (await starter.count()) await starter.click();
    else await modal.getByRole('link', { name: 'Use template', exact: true }).first().click();
    await modal.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector("#section-heading").textContent === "Supply trunk branch takeoff");
    await page.keyboard.press('Escape');
    assert.deepEqual(prompts, ['confirm']);
    assert(await modal.evaluate(dialog => dialog.matches(':modal')));
    accept = true;
    await modal.getByRole('button', { name: 'Back to path', exact: true }).click();
    assert.equal(await page.locator('#path-name').inputValue(), 'Retain this original draft');
    assert.equal(await page.locator('#path-straight').inputValue(), '10, 15');
    assert.equal(await page.locator('#path-rows').innerText(), draftRows);
    assert(await page.locator('#path-from-template').evaluate(node => node === document.activeElement));
    await page.locator('#path-from-template').click();
    await modal.getByRole('link', { name: 'Use template', exact: true }).first().click();
    await modal.locator('[data-action=browse]').click();
    await page.locator('#browse-fittings').waitFor();
    await page.keyboard.press('Escape');
    assert(await modal.evaluate(dialog => dialog.matches(':modal')));
    assert.equal(await page.locator('#browse-fittings').evaluate(dialog => dialog.open), false);
    await modal.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector("#section-heading").textContent === "Supply trunk branch takeoff");
    await modal.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.waitForURL(listURL);
    assert.deepEqual(prompts, ['confirm', 'confirm', 'confirm'], 'No native beforeunload warning on template transitions or confirmed cancellation');
    assert.deepEqual(errors, []);
    console.log('PASS: modal takeover, preserved original rows and fields, Back focus, nested Escape, declined discard, confirmed cancellation, and no leave-site warnings.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
