// Run against a disposable application. Creates a user, template, and project.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const base = process.env.FITTING_APP_URL || 'http://localhost:8081';
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
    const password = require('node:crypto').randomUUID();
    const signup = await context.request.post(base + '/signup', { form: { email: `template-browser-${Date.now()}@example.test`, password, confirmPassword: password } });
    const userID = (await signup.text()).match(/name="userID" value="([^"]+)"/)[1];
    await context.request.post(base + '/signup/profile', { form: { userID, firstName: 'Template', lastName: 'Review', companyName: 'QA', streetAddress: '1 Test Street', city: 'Cincinnati', state: 'OH', zipCode: '45202', theme: 'dark' } });
    const project = await context.request.post(base + '/projects', { form: { name: 'Template browser review', streetAddress: '1 Test Street', city: 'Cincinnati', state: 'OH', zipCode: '45202' } });
    const projectID = (await project.text()).match(/projects\/([0-9A-Fa-f-]{36})/)[1];
    const page = await context.newPage(), errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    await page.goto(base + '/path-templates/new/supply');
    await page.locator('[data-config=name]').fill('Browser reviewed supply');
    await page.locator('[data-config=name]').press('Tab');
    const downloaded = page.waitForEvent('download');
    await page.locator('[data-action=export-template]').click();
    const file = await downloaded, exportPath = await file.path();
    const exported = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
    assert.equal(exported.name, 'Browser reviewed supply');
    assert.equal(exported.steps.length, 5);
    assert.equal(await page.locator('[data-theme=dark]').count(), 1);
    await page.screenshot({ path: '/tmp/templates-editor-desktop.png', animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: '/tmp/templates-editor-mobile.png', animations: 'disabled' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('[data-action=try]').click();
    await page.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Supply trunk branch takeoff');
    await page.locator('[data-action=exit-trial]').first().click();
    assert.equal(await page.locator('[data-config=name]').inputValue(), 'Browser reviewed supply');
    await page.locator('[data-action=save-template]').click();
    await page.waitForURL(/\/path-templates\/[0-9A-Fa-f-]{36}$/);
    const templateID = page.url().split('/').pop();
    await page.goto(`${base}/projects/${projectID}/effective-lengths`);
    assert.equal(await page.getByRole('link', { name: 'Add equivalent length', exact: true }).count(), 1);
    await page.getByRole('link', { name: 'From template', exact: true }).click();
    await page.getByRole('link', { name: 'Use template', exact: true }).click();
    await page.locator('[data-action=choose][data-id="1B"]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Supply trunk branch takeoff');
    await page.locator('[data-action=skip]').click();
    await page.locator('[data-action=choose][data-id="4G"]').click();
    await page.locator('[data-quantity="8A-4-or-5-piece"]').fill('2');
    await page.locator('[data-action=done]').click();
    await page.waitForFunction(() => document.querySelector('#section-heading').textContent === 'Transitions');
    await page.locator('[data-action=skip]').click();
    await page.locator('[data-path=name]').fill('Guided browser path');
    await page.locator('[data-path=straight]').fill('10');
    await page.locator('[data-action=save-path]').click();
    await page.waitForURL(`**/projects/${projectID}/effective-lengths`);
    await page.getByRole('link', { name: 'Edit', exact: true }).click();
    await page.waitForURL(/\/guided\/edit\//);
    const saved = JSON.parse(await page.locator('#path-template-data').textContent()).path;
    assert.equal(saved.templateSnapshot.templateID, templateID);
    assert.equal(saved.groups.length, 3);
    assert.equal(saved.groups[2].quantity, 2);
    assert.equal(saved.groups[2].fitting.calculation.catalogRevision, 'fitting-catalog-v14');
    await page.screenshot({ path: '/tmp/templates-guided-desktop.png', animations: 'disabled' });
    await page.goto(base + '/path-templates/import');
    await page.locator('#import-template-file').setInputFiles(exportPath);
    await page.locator('[data-action=import-template]').waitFor();
    await page.locator('[data-action=import-template]').click();
    await page.waitForURL(/\/path-templates\/[0-9A-Fa-f-]{36}$/);
    assert.notEqual(page.url().split('/').pop(), templateID);
    assert.deepEqual(errors, []);
    console.log('PASS: template editor, actual JSON download/import, independent Try, desktop/mobile theme, existing picker entry, guided save/reopen, and current catalog snapshots.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
